# See https://hub.docker.com/r/tweag/linear-types/
resolver: lts-16.15
compiler: ghc-9.1
allow-newer: true
system-ghc: true

packages:
- '.'

extra-deps:
- git: https://github.com/tweag/linear-base.git
  commit: 7e5504f87c15e2d3a5096b4f3b86d8a618cf6fb0

nix:
  enable: true
  shell-file: shell-stack.nix
  path: ["nixpkgs=./nixpkgs.nix"]