name: Cache

on: [push]

jobs:

  cache:
    runs-on: macos-latest
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v12
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v8
      with:
        name: amarrella
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
    - run: nix-build shell.nix -A inputDerivation
    - run: nix-build shell-stack.nix -A inputDerivation
